Rebrand account card
aeternity/superhero-wallet pull request #1148
Opened 2021-06-25 06:38 UTC by etharner

2021-06-30 02:51 UTC, CedrikNikita commented on src/icons/account-card/collapse.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
```suggestion
<svg viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
```

2021-06-30 02:51 UTC, CedrikNikita commented on src/icons/account-card/expand.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
```suggestion
<svg viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
```
```suggestion
<svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
```

2021-06-30 02:51 UTC, CedrikNikita commented on src/popup/router/components/AccountCard.vue
> +      { subaccount: idx !== 0, 'first-subaccount': idx === 1 }]"
Why do we need this changes?

2021-06-30 02:51 UTC, CedrikNikita commented on src/popup/router/components/AccountSwitcher.vue
> +  margin-bottom: 24px;
margin with `.buttons` should be 12px (clarify in designs),
without should be 16px

2021-06-30 02:51 UTC, CedrikNikita commented on src/popup/router/components/AccountCard.vue
> -    <div class="arrows">
class="arrow" related css should be also removed
https://github.com/aeternity/superhero-wallet/blob/44939e695dd12c46738e1e5c1a99359bb4163849/src/popup/router/components/AccountCard.vue#L95-L118

2021-06-30 02:51 UTC, CedrikNikita commented on src/popup/router/components/AccountInfo.vue
> +          v-if="UNFINISHED_FEATURES && idx === 0"
```suggestion
          v-if="UNFINISHED_FEATURES"
```
Seems that `createAccount` button should be visible in each card. Can you elaborate on this @paolomolo?

2021-06-30 02:51 UTC, CedrikNikita commented on src/popup/router/components/AccountInfo.vue
> +          v-if="idx !== 0 && $route.path === '/accounts'"
Account with idx=0 can be deleted now aswell, there should be different wording for this case aswell

2021-06-30 02:53 UTC, CedrikNikita commented
AccountCard also is 16px smaller, than it should be

2021-06-30 10:46 UTC, paolomolo commented
Feedback for the account cards, in general please update margins and spacings as in the prototype. Thanks!

**account card**:
- width: 328px
- margin to left and right screen edge: 16px
- margin-top to navbar: 12px
- margin to green account switcher tabs: 12px
- margin to next card: 4px
- remove downward animation on slide into view
- add hotspot on next card to slide it into view
- add drag navigation to navigate
- please review spacing for account card settings screen
- improve collaps animation:
  - add `overflow: hidden` to account card to hide balance with animation

---

**account switcher tabs**:
- height: 10px (without border)
- bottom margin: 12px

---
 
**account card action buttons** (copy, plus, settings):
- spacing between: 8px (remove whitespace)

2021-07-02 08:03 UTC, etharner commented
> Feedback for the account cards, in general please update margins and spacings as in the prototype. Thanks!
> 
@paolomolo I've fixed everything beside user gestures, I think it should be done separately to separate stylistic and algorithmic changes

2021-08-13 06:03 UTC, CedrikNikita approved these changes
Since this changes only style/markup related, the rest of logic changes could be made in other PR.

2021-08-17 03:15 UTC, CedrikNikita requested changes

2021-08-17 03:15 UTC, CedrikNikita commented on src/popup/App.vue
> +      }
I did not undestand the purpose of this code

2021-08-17 03:20 UTC, merged