Fixes for TransactionList
aeternity/superhero-wallet pull request #1230
Opened 2021-07-20 13:05 UTC by imollov

fixes #1228
fixes #1211
fixes #1195

2021-07-21 03:54 UTC, CedrikNikita commented
![loading](https://user-images.githubusercontent.com/9008074/126428387-7a5d5f10-ad8d-41fe-84ba-d850ff53bd97.gif)

2021-07-21 07:26 UTC, etharner commented on src/popup/router/components/TransactionList.vue
> +      v-else-if="!filteredTransactions.length"
How can I reproduce it? I have this message on newly created account on develop version:
![image](https://user-images.githubusercontent.com/7098449/126448663-4dff1e0c-6129-42c2-aebe-7dd7baf69dd2.png)

2021-07-21 07:30 UTC, etharner commented on src/popup/router/components/TransactionList.vue
> +      v-else-if="!filteredTransactions.length"
Ok, got it, it's after filtering

2021-07-21 13:17 UTC, imollov commented
> ![loading](https://user-images.githubusercontent.com/9008074/126428387-7a5d5f10-ad8d-41fe-84ba-d850ff53bd97.gif)

This is reproducible on develop. 

I propose to not show the loader when fetching next page for now as it's not in the designs either.

2021-07-22 02:26 UTC, CedrikNikita commented
> 
> I propose to not show the loader when fetching next page for now as it's not in the designs either.

At this case user won't know that he scrolled to the bottom. I propose to drop last commit and merge the rest, since the issue i've mentioned was not supposed to be fixed within this PR.

2021-07-22 09:01 UTC, CedrikNikita requested changes

2021-07-22 09:01 UTC, CedrikNikita commented on src/popup/router/components/TransactionList.vue
> -        this.checkLoadMore();
Without this check we will get in the situation like this, when the chunk contain not enought info to fill the whole height, and the user is not able to scroll to the bottom cause of that
![Ivelin](https://user-images.githubusercontent.com/9008074/126613995-c57a314c-5ed0-4e1f-8814-dbc3d9a5acda.gif)
or even like this:

this PR
![image](https://user-images.githubusercontent.com/9008074/126614236-77e860b3-6c13-40e9-ba85-d048c0bc3be2.png)

develop
![image](https://user-images.githubusercontent.com/9008074/126614319-d8017fc1-ad7c-4448-82d5-39e6b092b01b.png)

2021-08-13 06:34 UTC, CedrikNikita commented
I still have an infinite loading
![Ivelin new](https://user-images.githubusercontent.com/9008074/129314944-ae278bbb-041d-4889-a401-93d7bbefa527.gif)

2021-08-16 09:04 UTC, imollov commented
> I still have an infinite loading
> ![Ivelin new](https://user-images.githubusercontent.com/9008074/129314944-ae278bbb-041d-4889-a401-93d7bbefa527.gif)

I couldn't fix it with the current implementation of load more behavior.

https://github.com/aeternity/superhero-wallet/issues/1234

> At this case user won't know that he scrolled to the bottom. I propose to drop last commit and merge the rest, since the issue i've mentioned was not supposed to be fixed within this PR.

Agreed.

2021-08-16 10:08 UTC, CedrikNikita approved these changes

2021-08-16 11:25 UTC, merged