fix(transactions): show tipped url only in transaction with function equal to 'tip'
aeternity/superhero-wallet pull request #1437
Opened 2022-05-06 13:06 UTC by pstachel

2022-05-16 09:37 UTC, CedrikNikita requested changes
This will result in excluding dex swap transactions from the TransactionList.

2022-05-16 13:38 UTC, pstachel commented
@CedrikNikita dex swap transactions are not excluded from transaction list (at least in my case) - it removes them only when we select "Tips" filter

2022-05-19 14:16 UTC, CedrikNikita commented
> @CedrikNikita dex swap transactions are not excluded from transaction list (at least in my case) - it removes them only when we select "Tips" filter

It is my mistake, i was looking at something else.

2022-05-19 14:17 UTC, CedrikNikita approved these changes

2022-05-21 18:06 UTC, merged