Add dex contracts and resolvers
aeternity/superhero-wallet pull request #1486
Opened 2022-06-30 07:27 UTC by CedrikNikita

links to the contacts:
- https://github.com/aeternity/dex-contracts-v2/blob/master/contracts/WAE.aes
- https://github.com/aeternity/dex-contracts-v2/blob/master/contracts/router/AedexV2Router.aes

link to the list of contracts:
- https://github.com/aeternity/dex-ui/issues/361

2022-06-30 10:38 UTC, pstachel requested changes

2022-06-30 10:38 UTC, pstachel commented on src/popup/utils/transactionTokenInfoResolvers.js
> +    || (!poolTokenAmountMapper && transaction.tx.return.type === 'list'))) {
maybe we could introduce enum for `transaction.tx.return.type`?

2022-06-30 10:38 UTC, pstachel commented on src/popup/utils/transactionTokenInfoResolvers.js
> +      isReceived: liquidityMethod === 'remove',
same here - maybe we should introduce enum for `liquidityMethod`?

2022-07-05 08:02 UTC, ifaouibadi approved these changes

2022-07-05 08:03 UTC, merged