[SW-80] DEX token – Label in token list
aeternity/superhero-wallet pull request #1497
Opened 2022-07-13 08:05 UTC by ifaouibadi

2022-07-13 08:26 UTC, pstachel requested changes

2022-07-13 08:26 UTC, pstachel commented on src/popup/router/components/FungibleTokens/TokensListItem.vue
> +  // height: 48px;
should we leave it here?

2022-08-04 09:26 UTC, pstachel requested changes

2022-08-04 09:26 UTC, pstachel commented on src/popup/router/components/FungibleTokens/TokensListItem.vue
> +
do we need that empty space here?

2022-08-04 10:07 UTC, merged

2022-08-04 10:21 UTC, CedrikNikita commented on src/popup/utils/constants.js
> +export const LEDGER_BRIDGE_URL = 'https://wallet.superhero.com/ledger-bridge';
That is a rebase mistake.