feat: adjust transaction confirmation modals to be DEX compatible
aeternity/superhero-wallet pull request #1513
Opened 2022-07-27 21:14 UTC by pstachel

2022-07-29 09:54 UTC, CedrikNikita reviewed
- **fix** error on initing the popup (waiting for sdk being trully to get a compilerApi), was **not** loading any data at all
`TypeError: Cannot read properties of null (reading 'compilerApi')`
- remove unused getters
- **fix** wrong showing of which token is `from` and which is `to` for the swap
- **fix**: there was not enough info for transactions: Allowance and AE related
- **fix**: new labels were not shown
- **fix**: additional information was loading only for the testnet
- **fix**: do not load additional info for a none contractCall transaction
- **fix**: do not show pool label for the allowance transactions

2022-07-29 09:54 UTC, CedrikNikita commented on src/popup/router/components/Modals/ConfirmTransactionSign.vue
> +        { tx: { ...txParams, ...this.transaction } }, this.availableTokens,
**fix**: there was not enough info for transactions: Allowance and AE related
![image](https://user-images.githubusercontent.com/9008074/181733917-b4b8dbd8-82f1-4fdd-9e53-c40985835bec.png)
![image](https://user-images.githubusercontent.com/9008074/181733936-c3882915-6478-48ca-a7df-e007f9d04cda.png)

2022-07-29 09:54 UTC, CedrikNikita commented on src/popup/router/components/Modals/ConfirmTransactionSign.vue
> +        await this.$watchUntilTruly(() => this.sdk);
**fix** error on initing the popup (waiting for `sdk` being trully to get a `compilerApi`), was not loading any data at all
`TypeError: Cannot read properties of null (reading 'compilerApi')`

2022-07-29 09:54 UTC, CedrikNikita commented on src/popup/router/components/Modals/ConfirmTransactionSign.vue
> +    <TransactionOverview :tx="completeTransaction" />
**fix**: new labels were not shown

2022-07-29 09:54 UTC, CedrikNikita commented on src/popup/router/components/Modals/ConfirmTransactionSign.vue
> +        const { bytecode } = await fetchJson(`${this.activeNetwork.url}/v3/contracts/${this.transaction.contractId}/code`);
**fix**: additional information was loading only for the testnet

2022-07-29 09:54 UTC, CedrikNikita commented on src/popup/router/components/Modals/ConfirmTransactionSign.vue
> +    if (this.transaction.contractId) {
**fix**: do not load additional info for a none conractCall transaction

2022-07-29 11:26 UTC, ifaouibadi commented on src/popup/router/components/Modals/ConfirmTransactionSign.vue
> +        const { bytecode } = await fetchJson(`${this.activeNetwork.url}/v3/contracts/${this.transaction.contractId}/code`);
```suggestion
        const { bytecode } = await this.sdk.;
```

2022-07-29 11:28 UTC, ifaouibadi commented on src/popup/router/components/Overview.vue
> +      return this.$te(`transaction.dexType.${getDexTransactionTag[this.txFunction] || this.txFunction}`)
```suggestion
      return this.$t(`transaction.dexType.${getDexTransactionTag[this.txFunction] || this.txFunction}`)
```

2022-07-29 11:32 UTC, ifaouibadi requested changes

2022-07-29 11:32 UTC, ifaouibadi commented on src/popup/router/pages/TransactionDetails.vue
> +      'getTxType',
```suggestion
     
```
since it's not used

2022-08-03 00:03 UTC, CedrikNikita commented on src/popup/router/components/Overview.vue
> +      return this.$te(`transaction.dexType.${getDexTransactionTag[this.txFunction] || this.txFunction}`)
https://github.com/aeternity/superhero-wallet/pull/1492#discussion_r933164306

2022-08-03 07:08 UTC, CedrikNikita commented
Wrong token amount is shown.
![Wrong token](https://user-images.githubusercontent.com/9008074/182545772-8c9f530e-bec2-4192-9a0e-b34ea9797ae5.gif)

2022-08-04 00:21 UTC, CedrikNikita commented
![image](https://user-images.githubusercontent.com/9008074/182737085-ddc5d972-7a5e-49e3-bf4a-87be51a5ca49.png)

2022-08-04 00:52 UTC, CedrikNikita commented on src/popup/router/components/TransactionDetailsPoolTokenRow.vue
> +<template>
Don't see a good reason to extract this component.

2022-08-08 09:26 UTC, merged