[Sw-109] Account details popup
aeternity/superhero-wallet pull request #1514
Opened 2022-07-29 10:35 UTC by ifaouibadi

2022-08-03 01:31 UTC, CedrikNikita reviewed
Is this behaviour is intendent @paolomolo?

![Account popup behaviour](https://user-images.githubusercontent.com/9008074/182504626-f1d9e0d4-3ba1-47a5-8cb7-3a397d99d9d3.gif)

2022-08-08 10:14 UTC, pstachel requested changes

2022-08-08 10:14 UTC, pstachel commented on src/popup/router/components/Modals/AccountDetails.vue
> +          </ButtonPlain>
To not repeat the code I'd suggest to make an array with all the tab names
```
tabs: ['tokens', 'transactions', 'names'],
```

and then iterate through them with v-for

```
<ButtonPlain
            v-for="tab in tabs"
            :key="tab"
            :class="{ active: activeTab === tab }"
            @click.prevent="setActiveTab(tab)"
          >
            {{ $t(`pages.account-details.${tab}') }}
          </ButtonPlain>
```

Of course translation strings should be adjusted accordingly

2022-08-08 10:14 UTC, pstachel commented on src/popup/router/components/Modals/AccountDetails.vue
> +    overflow: hidden;
```suggestion
    overflow: hidden auto;
```

or 
```
overflow-x: hidden;
overflow-y: auto;
```

2022-08-08 10:14 UTC, pstachel commented on src/popup/router/components/Modals/AccountDetails.vue
> +      align-items: center;
You could use flex mixin

2022-08-08 10:14 UTC, pstachel commented on src/popup/router/components/TransactionList.vue
> +        // date: { rotated: true },
do we still need it?

2022-08-11 08:03 UTC, CedrikNikita commented on src/popup/router/components/Modals/AccountDetails.vue
> +    if (this.$refs.account_details) {
We have an agreement to name variables in camelCase.

2022-08-11 08:03 UTC, CedrikNikita commented
You need to fix all the lgtm-bot problems, plus first commit looks weird.

2022-08-12 10:32 UTC, CedrikNikita commented on src/popup/router/components/AccountCard.vue
> +    </div>
```suggestion
    <AccountInfo
      v-bind="$attrs"
      :color="color"
      @click.native.stop
    />
```

2022-08-12 10:32 UTC, CedrikNikita commented on src/popup/router/components/AccountCard.vue
> +        @click.stop=""
```suggestion
        @click.stop
```

2022-08-19 10:57 UTC, merged