[SW-18] Send modal
aeternity/superhero-wallet pull request #1534
Opened 2022-08-19 13:29 UTC by peronczyk

2022-09-07 13:12 UTC, CedrikNikita commented
Except of additional commits
Introduced additional changes in this PR on top of what already have been done:
- add logic for every type of send action
- **fix**: deeplinks to `/tips`
- **fix**: openwith funcitonality (sharing via wallet)
- **fix**: validation of fields
- **fix**: disabling of next button
- **fix**: retip page
- **fix**: prefill send modal if selectedToken prop is not null
- **fix**: success send modal being full screen instead of fitting the app width, height
- **fix**: showing nan as AE price if balance is 0
- **fix(name-item)**: show name properly on (error condition was broken)
- **refactor(token-details)**: remove unused code
- **refactor(send)**: remove unused code
- **fix(helpers)**: escapeSpecialChars default value
- **test**: make them work

2022-09-07 13:37 UTC, pstachel requested changes

2022-09-07 13:37 UTC, pstachel commented on src/popup/router/components/Modals/ConfirmTip.vue
> +    <!--     TODO - pawel - remove probably -->
can be removed :)

2022-09-07 13:37 UTC, pstachel commented on src/popup/router/components/Modals/RecipientHelper.vue
> +        >
Maybe we should rely on UNFINISHED_FEATURES flag here?

2022-09-07 13:37 UTC, pstachel commented on src/popup/router/components/Modals/RecipientInfo.vue
> +        <p v-if="false">
Maybe we should rely on UNFINISHED_FEATURES flag here?

2022-09-07 13:37 UTC, pstachel commented on src/popup/router/components/TransferSendForm.vue
> +    }
Those color should come from variables

2022-09-07 13:37 UTC, pstachel commented on src/store/plugins/pendingTransactionHandler.js
> +      // TODO - pawel - close tx modal
This TODO should be removed

2022-09-07 13:53 UTC, peronczyk commented on src/popup/router/components/InputAmount.vue
> +      <span class="token">{{ 'AE' }}</span>
```suggestion
      <span class="token">AE</span>
```

No need to use moustache here.

2022-09-07 13:53 UTC, peronczyk commented on src/popup/router/components/InputField.vue
> +    :class="[{
No need to wrap the object with an array.

2022-09-07 13:53 UTC, peronczyk commented on src/popup/router/components/Modals/ConfirmTip.vue
> +    <!--     TODO - pawel - remove probably -->
@pstachel ?? :)

2022-09-07 13:53 UTC, peronczyk commented on src/popup/router/components/Modals/ConfirmTip.vue
> +    <template slot="header">
`#header`

2022-09-07 13:53 UTC, peronczyk commented on src/popup/router/components/Modals/ConfirmTip.vue
> +    <p class="confirmation--question">
I would be really happy to use BEM, but we are not using it currently. So I think one dash should be used.

2022-09-08 02:53 UTC, CedrikNikita commented on src/popup/router/components/Modals/QrCodeReader.vue
> +          document.querySelector('.transfer-send-modal').style.display = 'none'; // TODO: refactor cordova qr code reading
It's a temporary decision, we should move it to the issues after merge.

2022-09-08 08:43 UTC, CedrikNikita commented on src/popup/router/components/AccountRow.vue
> +  <div class="account-row">
The name doesn't sound perfect for me, feel free to propose a different naming.

2022-09-08 11:03 UTC, merged