[SW-64, SW-65] seed phrase screens
aeternity/superhero-wallet pull request #1552
Opened 2022-09-05 13:28 UTC by ifaouibadi

2022-09-06 03:54 UTC, CedrikNikita commented on src/popup/router/pages/SeedPhraseDetailsSettings.vue
> +  }),
```suggestion
```
Both `error` and `view` is not used in this component.

2022-09-06 03:54 UTC, CedrikNikita commented on src/popup/router/pages/SeedPhraseDetailsSettings.vue
> +  }),
```suggestion
  computed: mapState(['mnemonic']),
```

2022-09-06 03:54 UTC, CedrikNikita commented on src/popup/router/pages/SeedPhraseVerifySettings.vue
> +    view: 'warning',
```suggestion
```
`view` is not used in this component.

2022-09-06 03:54 UTC, CedrikNikita commented on src/popup/router/pages/SeedPhraseVerifySettings.vue
> +    span {
https://github.com/aeternity/superhero-wallet/issues/986

2022-09-06 04:02 UTC, CedrikNikita commented
![seed phrase](https://user-images.githubusercontent.com/9008074/188544301-dcfcffc6-e323-4fa7-9473-c69ce454d034.gif)
For me that it does not fit the screen looks not user friendly

2022-09-08 12:09 UTC, konradodo commented on src/popup/router/pages/SeedPhraseDetailsSettings.vue
> +    border-radius: 10px;
$border-radius-interactive

2022-09-08 12:10 UTC, konradodo commented on src/popup/router/pages/SeedPhraseVerifySettings.vue
> +        @click.native="!selectedWordIds.includes(index) && selectedWordIds.push(index)"
create method

2022-09-08 12:15 UTC, pstachel requested changes
Also we should stick to naming components with CamelCase not kebab-case - it happens with all `ae-something` components

2022-09-08 12:15 UTC, pstachel commented on src/popup/router/pages/SeedPhraseVerifySettings.vue
> +      </ae-badge>
You shouldn't use v-for with v-if - it should be wrapped

2022-09-08 12:15 UTC, pstachel commented on src/popup/router/pages/SeedPhraseVerifySettings.vue
> +            Seed phrase words are not in the correct order. Please enter your seed phrase again!
I think it should be stored in en.json

2022-09-08 12:15 UTC, pstachel commented on src/popup/router/pages/SeedPhraseVerifySettings.vue
> +            Seed phrase has been verified!
It should be in en.json

2022-09-08 12:16 UTC, konradodo commented on src/popup/router/pages/SeedPhraseVerifySettings.vue
> +      border-radius: 10px;
variables

2022-09-08 12:58 UTC, pstachel approved these changes

2022-09-08 13:06 UTC, merged