[SW-193] Total wallet amount
aeternity/superhero-wallet pull request #1556
Opened 2022-09-07 12:10 UTC by pstachel

2022-09-07 13:04 UTC, peronczyk requested changes

2022-09-07 13:04 UTC, peronczyk commented on src/popup/router/components/AeBalance.vue
> +    <span class="token-integer">{{ `${balanceParts.integer}.` }}</span>
Integer part is already converted to string.

2022-09-07 13:43 UTC, pstachel commented on src/popup/router/components/AccountSwitcher.vue
> +    <TotalWalletAmount v-if="filteredAccounts.length > 1" />
Well, it's used only in account switcher and requires 'filteredAccounts' property from AccountSwitcher, so I think it should stay there

2022-09-08 05:22 UTC, CedrikNikita commented on src/popup/router/components/TotalWalletAmount.vue
> +    ...mapGetters(['convertToCurrencyFormatted', 'accounts']),
```suggestion
    ...mapGetters(['convertToCurrencyFormatted']),
```
`accounts` is not used in this component.

2022-09-08 05:22 UTC, CedrikNikita commented on src/popup/router/components/TotalWalletAmount.vue
> +      if (!this.balances) return 0;
https://github.com/aeternity/superhero-wallet/blob/67f25570223516b83792d9ffddc28e90daf484fa/src/store/plugins/observables.js#L66-L72

I don't think that this condition would work.

2022-09-08 10:51 UTC, peronczyk approved these changes

2022-09-08 12:19 UTC, konradodo commented on src/popup/router/components/AeBalance.vue
> +      const [integer, fraction] = this.balance.toFixed(2).toString().split('.');
toFixed(2) that return string

2022-09-08 12:27 UTC, merged