[SW-258] Move components and pages from popup/router/ dir to popup/ (one level up)
aeternity/superhero-wallet pull request #1610
Opened 2022-09-16 08:49 UTC by peronczyk

2022-09-16 11:55 UTC, pstachel requested changes

2022-09-16 11:55 UTC, pstachel commented on src/popup/components/Modals/ShareQr.vue
> +@use "../../../styles/variables";
Singlequotes should be used

2022-09-16 11:55 UTC, pstachel commented on src/popup/components/Modals/RecipientInfo.vue
> +@use '../../../styles/mixins';
Single quotes should be used

2022-09-16 11:55 UTC, pstachel commented on src/popup/components/Modals/RecipientHelper.vue
> +@use '../../../styles/typography';
Single quotes should be used

2022-09-19 09:36 UTC, peronczyk commented on src/popup/components/Modals/RecipientHelper.vue
> +@use '../../../styles/typography';
Fixed

2022-09-19 09:37 UTC, peronczyk commented on src/popup/components/Modals/ShareQr.vue
> +@use "../../../styles/variables";
Fixed

2022-09-19 10:07 UTC, pstachel approved these changes

2022-09-19 10:35 UTC, ifaouibadi approved these changes

2022-09-19 10:41 UTC, merged