fix: bell icon and notification badge [#1470]
aeternity/superhero-wallet pull request #1612
Opened 2022-09-21 09:30 UTC by konradodo

2022-09-21 09:35 UTC, pstachel requested changes
The icon shouldn't have width & height as well as the color should be set to `currentColor`

2022-09-21 09:35 UTC, pstachel commented on src/popup/components/Header.vue
> +      padding: 0 3.5px;
I think there is no thing as half of a pixel

2022-09-21 10:41 UTC, peronczyk requested changes

2022-09-21 10:41 UTC, peronczyk commented on src/popup/components/Header.vue
>      .badge {
I think we should have separate component for the badges.

2022-09-22 08:58 UTC, pstachel requested changes

2022-09-22 08:58 UTC, pstachel commented on src/popup/components/Header.vue
> +      const count = [...this.notifications, ...this.superheroNotifications].filter(
`this.notifications` and `this.superheroNotifications` may be undefined

2022-09-23 09:35 UTC, pstachel approved these changes

2022-09-28 09:26 UTC, peronczyk approved these changes

2022-09-28 09:27 UTC, merged