[SW-256] Token details screen
aeternity/superhero-wallet pull request #1621
Opened 2022-09-28 13:38 UTC by pstachel

2022-09-29 08:05 UTC, konradodo requested changes

2022-09-30 16:19 UTC, pstachel commented on src/popup/components/FungibleTokens/TokenDetailsInfo.vue
> +          :class="{
It's used only once

2022-09-30 16:19 UTC, pstachel commented on src/popup/components/FungibleTokens/TokenDetailsInfo.vue
> +          {{ Number(tokenData.price_change_percentage_24h).toFixed(2) }}%
Same as above

2022-10-06 07:15 UTC, peronczyk commented on src/popup/components/FungibleTokens/TokenDetailsInfo.vue
> +        {{ formatCurrency(tokenData.total_volume) }}
This can be passed as a prop instead of slot.

2022-10-06 07:18 UTC, peronczyk commented on src/popup/components/FungibleTokens/TokenDetailsInfo.vue
> +      return this.DEX_URL.replace('https://', '');
`DEX_URL` is imported above so I suggest to not use the `this.` as it's not necessary.

2022-10-06 07:19 UTC, peronczyk commented on src/popup/components/FungibleTokens/TokenDetailsInfo.vue
> +import { convertToken } from '../../utils/helper';
If you rebase to current develop you could skip the `/helper` part of the path.

2022-10-06 07:21 UTC, peronczyk commented on src/popup/components/FungibleTokens/TokensListItem.vue
> +      name: tokenData.contractId === AETERNITY_CONTRACT_ID ? 'coin-details' : 'token-details',
Now in my opinion there's too much logic here. I suggest to move it to computed proprty.

2022-10-06 07:24 UTC, peronczyk commented on src/popup/components/FungibleTokens/TokenDetailsInfo.vue
> +export default {
Maybe you could use TypeScript here :)
(only a suggestion, skip it if you want)
Here's an example that you can base of: https://github.com/aeternity/superhero-wallet/blob/refactor/replace-mixin-copy-with-composable/src/popup/components/Modals/TransferReceive.vue

2022-10-06 07:27 UTC, peronczyk commented on src/popup/router/routes.js
> +    path: '/balancesx/:id',
`balancesx` in my opinion is meaningless. I suggest to make the path closer to the name.
Eg.:
`/balances/token/:id`
`/balances-token/:id`

2022-10-06 12:30 UTC, peronczyk commented on src/popup/components/FungibleTokens/TokenDetailsInfo.vue
> +  .price ::v-deep .text {
No need to use v-deep here as the green and red exists in current scope.

2022-10-06 12:30 UTC, peronczyk commented on src/popup/components/FungibleTokens/TokenDetailsInfo.vue
> +  .link ::v-deep .text a {
Same here.

2022-10-06 12:31 UTC, peronczyk commented on src/popup/components/FungibleTokens/TokenDetailsInfo.vue
> +  ::v-deep .address-shortening {
Please avoid using v-deep

2022-10-06 12:32 UTC, peronczyk commented on src/popup/pages/AccountDetailsTransactions.vue
> +  ::v-deep .filters {
Please avoid using v-deep.

2022-10-06 12:33 UTC, peronczyk commented on src/popup/router/routes.js
> +    path: '/balances/:id',
Now this path is the same one as line 464. This can cause problems.

2022-10-06 13:08 UTC, konradodo commented on src/popup/components/FungibleTokens/TokenDetailsInfo.vue
> +      v-if="tokenPairs.token0 && tokenPairs.token0.amount > 0"
tokenPairs.token0?.amount > 0

2022-10-06 13:17 UTC, konradodo approved these changes

2022-10-06 13:22 UTC, peronczyk approved these changes

2022-10-11 08:26 UTC, merged