[SW-286] Fix broken input field
aeternity/superhero-wallet pull request #1623
Opened 2022-09-29 16:28 UTC by pstachel

2022-10-06 09:45 UTC, peronczyk requested changes

2022-10-13 11:37 UTC, konradodo approved these changes

2022-10-17 13:30 UTC, peronczyk requested changes

2022-10-17 13:30 UTC, peronczyk commented on src/popup/components/InputField.vue
> +    checkModifierKey(event) {
In my opinion there is no need to create separate method for this logic as it's used only once.

2022-10-17 13:30 UTC, peronczyk commented on src/popup/components/InputField.vue
> +      if ((this.value?.includes('.') && [',', '.'].includes(event.key)) || !/^([0-9]+|,|\.)$/.test(event.key)) {
This should be `else if`.

2022-10-17 13:30 UTC, peronczyk commented on src/popup/components/InputAmountV2.vue
> +    inputmode="decimal"
In my opinion this should be moved into InputField component and be based on input type.

2022-10-17 13:30 UTC, peronczyk commented on src/popup/components/InputAmount.vue
> +    inputmode="decimal"
In my opinion this should be moved into InputField component and be based on input type.

2022-10-20 08:44 UTC, peronczyk requested changes

2022-10-20 08:44 UTC, peronczyk commented on src/popup/components/InputField.vue
> +      if (!(this.type !== 'number' || event.key.length > 1 || ['ctrlKey', 'metaKey'].some((key) => event[key]))
With the multiline if statements I suggest to do the same approach as with the object properties. So we are able to do this:
```
{ a: 1, b: 2, c: 3 }
```
and this:
```
{
  a: 1,
  b: 2,
  c: 3
}
```
Nothing in between, so this is wrong:
```
{ a: 1, b: 2,
c: 3 }
```
I think the same rule should be applied to if statements. So I suggest to do it as follows:
```
if (
  (test1 || test2 || test3)
  && (test4 || test5)
  && test6
) {
  ...
}
```

2022-10-21 08:35 UTC, peronczyk approved these changes

2022-10-31 09:28 UTC, merged