fix: top bar style
aeternity/superhero-wallet pull request #1633
Opened 2022-10-09 21:15 UTC by konradodo

2022-10-10 08:26 UTC, pstachel requested changes

2022-10-10 08:26 UTC, pstachel commented on src/popup/components/Header.vue
> +        </BtnPlain>
You should use BtnIcon for it

2022-10-10 08:26 UTC, pstachel commented on src/popup/components/Header.vue
> +            title ? $t(`pages.titles.${title}`) : ''"
I'd suggest moving it into computed

2022-10-10 11:01 UTC, peronczyk requested changes

2022-10-10 11:01 UTC, peronczyk commented on src/icons/logo-header.svg
> +<svg width="33" height="32" viewBox="0 0 33 32" fill="none" xmlns="http://www.w3.org/2000/svg">
After some testing I think adding new logo file makes new sensy as the old one was OK. The size difference could be fixed by changing CSS.

2022-10-10 11:16 UTC, konradodo commented on src/popup/components/Header.vue
> +        </BtnPlain>
@peronczyk so i leave it now as agreed.

2022-10-10 11:51 UTC, peronczyk requested changes

2022-10-10 11:51 UTC, peronczyk commented on src/popup/components/Header.vue
>      svg {
This styles can be moved to `.home-icon`.

2022-10-10 12:35 UTC, pstachel approved these changes

2022-10-11 07:11 UTC, peronczyk approved these changes

2022-10-12 08:10 UTC, merged