[SW-294] closable dashboard cards
aeternity/superhero-wallet pull request #1647
Opened 2022-10-18 07:12 UTC by ifaouibadi

2022-10-18 07:54 UTC, pstachel requested changes

2022-10-18 07:54 UTC, pstachel commented on src/popup/components/dashboard/Card.vue
> +    v-if="!closable || (!hiddenCards || !hiddenCards.includes(closable))"
Bracket isn't needed
```suggestion
    v-if="!closable || !hiddenCards || !hiddenCards.includes(closable)"
```

2022-10-18 10:52 UTC, konradodo approved these changes

2022-10-18 13:21 UTC, peronczyk requested changes

2022-10-18 13:21 UTC, peronczyk commented on src/popup/components/dashboard/Card.vue
> +      </BtnPlain>
I suggest to use the BtnClose component, or BtnIcon.

2022-10-18 13:21 UTC, peronczyk commented on src/popup/components/dashboard/Card.vue
> +  components: { BtnPlain, Close },
Please put each component in separate lines to avoid conflicts in the future changes.

2022-10-18 13:21 UTC, peronczyk commented on src/popup/components/dashboard/Card.vue
> +    closable: { type: String, default: null },
Name 'closable' suggests that this is a boolean.
For the readability purpose I suggest to add another prop, eg.: `cardId` or `cardSlugName`.

2022-10-18 13:21 UTC, peronczyk commented on src/popup/components/dashboard/Card.vue
> +  position: relative;
I suggest to use this patterns to organise CSS properties: https://9elements.com/css-rule-order/

2022-10-18 13:21 UTC, peronczyk commented on src/popup/components/dashboard/Card.vue
>    <div
To make the UI smoother I suggest to wrap this element with a fade transition.

2022-10-19 09:00 UTC, peronczyk requested changes

2022-10-19 09:00 UTC, peronczyk commented on src/popup/components/dashboard/Card.vue
> +      v-if="!cardId || !hiddenCards || !hiddenCards.includes(cardId)"
I don't see a reason for hiding the card if there is no `cardId` and if there are no `hiddenCards`.
Also I suggest to put this kind of logic under `isVisible` computed the debugging easier.

2022-10-19 09:00 UTC, peronczyk commented on src/popup/components/buttons/BtnIcon.vue
> +  &.light {
I see a problem with the BtnIcon variants - there are no validation and no list of possible variants. I suggest to create a constant similar to `SIZES` and validate the `variant` prop same way as the `size`.

2022-10-24 08:08 UTC, peronczyk requested changes

2022-10-24 08:08 UTC, peronczyk commented on src/popup/components/dashboard/Card.vue
> +    .icon {
There is no `icon` class within the scope of this component.

2022-10-24 08:15 UTC, peronczyk approved these changes

2022-10-24 08:25 UTC, pstachel approved these changes

2022-10-24 08:31 UTC, merged