fix(transaction-overiew): show a proper name for transactions to sent to a name
aeternity/superhero-wallet pull request #1662
Opened 2022-10-28 10:53 UTC by CedrikNikita

https://github.com/aeternity/ae_mdw/blob/fe0e3bec4c7f24da6f2e9fdceabdbb46ea7b0d8e/priv/static/swagger/swagger.json#L2025

2022-10-28 10:57 UTC, pstachel requested changes

2022-10-28 10:57 UTC, pstachel commented on src/popup/pages/Dashboard.vue
> +    <button @click="test">
should it stay here?

2022-11-02 14:03 UTC, pstachel approved these changes

2022-11-02 14:11 UTC, peronczyk approved these changes

2022-11-02 14:13 UTC, merged