Fix: Prevent errors in case of connection errors
aeternity/superhero-wallet pull request #1674
Opened 2022-11-08 09:56 UTC by peronczyk

2022-11-13 09:28 UTC, pstachel requested changes

2022-11-13 09:28 UTC, pstachel commented on src/store/modules/accounts/ledger.js
> +          dispatch('modals/open', { name: 'default', icon: 'alert', title: 'account not found' }, { root: true });
use `MODAL_DEFAULT` constant

2022-11-13 11:14 UTC, subhod-i commented
I tested it and the bug doesn't exist anymore. Works as intended.

2022-11-14 12:37 UTC, pstachel approved these changes

2022-11-14 12:55 UTC, merged