[SW-513, SW-278] Change back button logic
aeternity/superhero-wallet pull request #1753
Opened 2022-12-20 11:14 UTC by CedrikNikita

also fixes the problem if the user will firstly open a page with a back buton, the back back button will return him to a empty browser new tab (introduced in #1743)

2022-12-20 18:48 UTC, pstachel approved these changes

2022-12-20 20:05 UTC, peronczyk requested changes

2022-12-21 15:26 UTC, CedrikNikita commented on src/popup/components/Header.vue
> +      );
This will result in moving to a concat of previous url with the `newPath` since there is no leading `/` in newPath.

2022-12-21 16:08 UTC, ifaouibadi approved these changes

2022-12-21 16:34 UTC, merged