Enable withdraw test
aeternity/superhero-wallet pull request #1783
Opened 2023-01-17 13:06 UTC by CedrikNikita

- on reviewing #1727, found out an error that could've been intercepted by this disabled test,
- our automated tests were overloading `api.coingecko` and it was throwing `429 (Too Many Requests)`, which resulting in a broken `balances` composable (#1782)

2023-01-17 13:33 UTC, peronczyk requested changes

2023-01-17 13:33 UTC, peronczyk commented on src/popup/utils/constants.ts
> +export const STUB_CURRENCY = [{
In my opinion we should keep the mocked data required for the tests in separate constants file located somewhere inside of the `tests/` directory.

Or maybe we can move this into the `src/popup/utils/config.js` file which is mostly used by the test files.

2023-01-17 15:20 UTC, peronczyk approved these changes

2023-01-18 09:32 UTC, pstachel approved these changes

2023-01-18 09:35 UTC, merged