[SW-606] Fix the design of Multisig Transaction Proposal modal
aeternity/superhero-wallet pull request #1846
Opened 2023-02-21 12:04 UTC by pstachel

2023-02-21 12:14 UTC, peronczyk approved these changes

2023-02-21 12:40 UTC, konradodo approved these changes

2023-02-24 09:33 UTC, ifaouibadi requested changes

2023-02-24 09:33 UTC, ifaouibadi commented on src/popup/components/AccountItem.vue
> +    &.rg {
```suggestion
    &.md {
```
I think `md` will make more sense

2023-02-24 10:39 UTC, ifaouibadi approved these changes

2023-02-24 10:43 UTC, konradodo approved these changes

2023-02-27 11:13 UTC, peronczyk approved these changes

2023-02-27 11:26 UTC, merged