fix: cleaning transaction after change multisig account
aeternity/superhero-wallet pull request #1850
Opened 2023-02-21 13:12 UTC by konradodo

2023-02-21 13:15 UTC, ifaouibadi approved these changes

2023-02-21 13:20 UTC, pstachel commented on src/popup/components/TransactionList.vue
> +      root.$store.commit('initTransactions');
I think that initTransaction is handled on account change - you could work on that or wait for SW-620 to be merged

2023-02-22 10:58 UTC, pstachel requested changes

2023-02-22 10:58 UTC, pstachel commented on src/popup/components/TransactionList.vue
>        if (loading.value) return;
if (loading.value) {
    return;
}

2023-02-22 10:58 UTC, pstachel commented on src/popup/components/TransactionList.vue
> -      });
why did we get rid of transaction polling?

2023-02-22 12:10 UTC, pstachel approved these changes

2023-02-22 15:03 UTC, peronczyk commented on src/popup/components/TransactionList.vue
> +                      && tr.tx.recipientId.startsWith('nm_')
By the way you can replace this with `isAensName` utility function.

2023-02-22 15:05 UTC, peronczyk approved these changes

2023-02-27 09:28 UTC, CedrikNikita requested changes
This PR is not fixing 654 completly, it is done in #1863.
I suggest to leave only a truncateWidth fix here.

2023-02-28 10:08 UTC, closed without merging