[SW-684] Disable URL tipping for URLs inside wallet
aeternity/superhero-wallet pull request #1916
Opened 2023-03-13 09:08 UTC by konradodo

2023-04-28 06:16 UTC, CedrikNikita commented
Check out how this feature works. Your code doesn't work for a redirect from `superhero.com`. 
https://feat-disabled-tips.wallet.z52da5wt.xyz/account?x-success=https%3A%2F%2Fsuperhero.com%2F&x-cancel=https%3A%2F%2Fsuperhero.com%2F

2023-04-28 06:16 UTC, CedrikNikita requested changes
Check out how this feature works. Your code doesn't work for a redirect from `superhero.com`. 
https://feat-disabled-tips.wallet.z52da5wt.xyz/account?x-success=https%3A%2F%2Fsuperhero.com%2F&x-cancel=https%3A%2F%2Fsuperhero.com%2F

2023-05-11 08:24 UTC, CedrikNikita commented on src/popup/components/TransferSendForm.vue
> +      const tipUrlEncoded: any = root.$route.query.url;
There are no more `url` in the query. And superhero is not providing such.

2023-05-11 10:32 UTC, subhod-i commented on src/popup/components/TransferSendForm.vue
> +          formModel.value.address = '';
`formModel.value.address` has been initialized twice.

2023-05-11 10:43 UTC, subhod-i approved these changes

2023-05-12 11:21 UTC, pstachel approved these changes

2023-05-12 19:41 UTC, CedrikNikita approved these changes
Code change look reasonable.

2023-05-15 08:42 UTC, merged