[SW-683] remove typing from third website
aeternity/superhero-wallet pull request #1927
Opened 2023-03-16 09:06 UTC by konradodo

2023-03-16 09:11 UTC, CedrikNikita requested changes
Commit message must not contain spelling mistakes.

2023-03-20 07:06 UTC, CedrikNikita reviewed
This is also breaking the chain name redirection script.

2023-03-20 07:10 UTC, CedrikNikita requested changes

2023-03-20 07:10 UTC, CedrikNikita commented on src/manifest.json
> -    "*://*.google.com/*",
Removal of this line is breaking the chain name redirection script.

2023-03-27 09:43 UTC, peronczyk approved these changes

2023-04-20 13:43 UTC, CedrikNikita requested changes
Injest.js is crucial

2023-04-20 13:44 UTC, davidyuk commented on src/content-scripts/inject.js
> -  }, 10);
This one should be needed for app-wallet connection

2023-04-20 14:44 UTC, subhod-i requested changes

2023-04-20 15:59 UTC, CedrikNikita commented on src/manifest.json
> -    "js/inject.js",
Should be returned back.

2023-04-28 08:08 UTC, CedrikNikita requested changes

2023-05-08 11:45 UTC, konradodo commented on src/content-scripts/inject.js
> -  const sendToBackground = (method, params) => new Promise((resolve) => {
@CedrikNikita can you check it now?

2023-05-09 09:06 UTC, subhod-i approved these changes

2023-05-10 06:51 UTC, CedrikNikita commented on src/store/plugins/tipUrl.js
> +      const url = tipUrl;
Why did you remove the `getTwitterAccountUrl` usage from here? It is not related to this task.

2023-05-10 07:11 UTC, ifaouibadi approved these changes

2023-05-10 09:43 UTC, CedrikNikita approved these changes

2023-05-10 09:57 UTC, merged

2023-07-03 09:48 UTC, davidyuk commented
Would be good to have motivation in a written form. Otherwise, it is unclear why this decision was made from an outside view.