[SW-608] Multiline input fields
aeternity/superhero-wallet pull request #1941
Opened 2023-03-21 14:36 UTC by konradodo

2023-03-21 14:51 UTC, pstachel commented on src/popup/components/Modals/MultisigVaultCreate.vue
> +import FormTextarea from '../form/FormTextarea.vue';
Please order the imports

2023-03-21 14:53 UTC, pstachel commented on src/popup/components/form/FormTextarea.vue
> +      if (!props.enterSubmit) return;
Or even clearer
```suggestion
      if (props.enterSubmit) {
         emit('submit');
      }
```

2023-03-22 10:28 UTC, pstachel approved these changes

2023-03-22 12:38 UTC, peronczyk commented on src/popup/components/form/FormTextarea.vue
> +          const { scrollHeight, clientHeight } = textarea.value as HTMLTextAreaElement;
Instead of using `as HTMLTextAreaElement` you probably can add `!` at the end of `textarea.value` to indicate it's defined.

2023-03-22 12:44 UTC, peronczyk requested changes

2023-03-22 12:44 UTC, peronczyk commented on src/popup/components/form/FormTextarea.vue
> +    const height = ref('auto');
I see that you choose to set the `auto` or `px` values. I was mentioning on priv that this is the worse solution, as from my experience it's causing some issues (it's less predictable). Here's an example:
![image](https://user-images.githubusercontent.com/8217670/226908253-2285f4da-5fec-486b-864c-1ee8ef194a3a.png)
(the scrollbar is visible).

2023-03-22 14:43 UTC, peronczyk approved these changes

2023-03-23 08:53 UTC, merged