[SW-799] Remove animation on Multisig transaction proposal detail page
aeternity/superhero-wallet pull request #1987
Opened 2023-04-12 11:15 UTC by pstachel

2023-04-13 12:05 UTC, peronczyk requested changes

2023-04-13 12:05 UTC, peronczyk commented on src/popup/components/Header.vue
> +    }
I think this styles should replace the styles used in the `BtnClose`. From my experience components should not position themselves.

2023-04-14 10:26 UTC, konradodo approved these changes

2023-04-18 07:35 UTC, ifaouibadi approved these changes

2023-04-18 11:16 UTC, peronczyk approved these changes

2023-04-18 11:17 UTC, merged