[SW-448] Performance update: disable data polling when on web and the tab is not active
aeternity/superhero-wallet pull request #2014
Opened 2023-04-20 15:20 UTC by pstachel

2023-04-20 15:29 UTC, CedrikNikita reviewed
I think it is more a `perf` than a `feat` type of a commit.

2023-04-27 13:15 UTC, peronczyk requested changes

2023-04-27 13:15 UTC, peronczyk commented on src/composables/visibilityChange.ts
I have few things to consider regarding this file:
1. I suggest to move the logic to `ui` composable.
2. I suggest to have a state `isAppActive` (or something similar).
3. Instead of stopping and running again the polling handler I suggest to run or prevent running the callback passed to polling handler based on the mentioned state. So the interval will be running all the time, but it won;t run anything when the tab is not active.
What do you think about this isea?

2023-04-27 13:15 UTC, peronczyk commented on src/popup/components/TransactionList.vue
> +import { createPollingBasedOnMountedComponents } from '../../composables/composablesHelpers';
In my opinion this is not a good change to use this composable helper inside of a component. The reason for this helper was to be used inside of the composables - functions used within many components. This is why it has the mounted components counter.

2023-04-27 13:15 UTC, peronczyk commented on src/popup/pages/Names/Auction.vue
> +import { createPollingBasedOnMountedComponents } from '../../../composables/composablesHelpers';
IDEM

2023-04-27 13:15 UTC, peronczyk commented on src/popup/pages/Names/List.vue
> +import { createPollingBasedOnMountedComponents } from '../../../composables/composablesHelpers';
IDEM

2023-04-27 13:45 UTC, pstachel commented on src/composables/visibilityChange.ts
Sure, I can proceed with that approach

2023-05-10 07:09 UTC, CedrikNikita approved these changes
Code changes look reasonable.

2023-05-15 22:21 UTC, peronczyk approved these changes

2023-05-15 22:23 UTC, merged