[SW-534, SW-821] Improve wording in the transaction list
aeternity/superhero-wallet pull request #2018
Opened 2023-04-21 09:29 UTC by pstachel

2023-04-28 06:42 UTC, peronczyk requested changes

2023-04-28 06:42 UTC, peronczyk commented on src/popup/components/ConsensusLabel.vue
> +    hasDot: Boolean,
This looks rather funny :) I suggest to align with Tsvetan if this component should end with dot or not.

2023-04-28 06:42 UTC, peronczyk commented on src/popup/components/ConsensusReachedLabel.vue
> +    const isConsensusReached = computed(
The component name is `Consesus Reached...` so by reading it I would assume that I should display it when the consensus is ready. But the logic encapsulated here states something opposite. So in my opinion the general naming convention is misleading here.

2023-05-02 11:13 UTC, konradodo approved these changes

2023-05-04 11:56 UTC, peronczyk commented on src/popup/components/ConsensusApprovedLabel.vue
> +      :has-dot="isConsensusReached"
I guess this can be removed.

2023-05-04 11:57 UTC, peronczyk commented on src/popup/components/ConsensusApprovedLabel.vue
> +      &hairsp;
Wrong indentation.

2023-05-04 13:27 UTC, merged