fix: Disable possibility of vault creation with chain name or an url
aeternity/superhero-wallet pull request #2025
Opened 2023-04-24 14:03 UTC by pstachel

2023-04-24 14:52 UTC, Liubov-crypto commented
LGTM on web and extension

2023-04-24 14:53 UTC, konradodo approved these changes

2023-04-25 09:15 UTC, peronczyk commented on src/composables/accounts.ts
> +  const accountsSelectOptions = computed(() => prepareAccountsSelectOptions(true));
I suggest to add empty line before this one.

2023-04-25 09:16 UTC, peronczyk commented on src/composables/accounts.ts
> +  const plainAccountSelectOptions = computed(() => prepareAccountsSelectOptions());
I suggest to rename this to `accountSelectOptionsPlain` to follow the same naming as the `accountSelectOptions`. Also I suggest to add empty line after this one.

2023-04-25 09:18 UTC, peronczyk commented on src/popup/components/Modals/MultisigVaultCreate.vue
> +            && !(root as any).$validator.errors.items?.length
Wrong indentation.

2023-04-25 09:23 UTC, peronczyk requested changes

2023-04-25 09:23 UTC, peronczyk commented on src/composables/accounts.ts
> +      listOnlyText: getAccountNameToDisplay(acc),
In my opinion this is bad to have a possibility of 2 properties with the same values (when the `withName` is set to `true`.

2023-04-25 09:25 UTC, peronczyk commented on src/composables/accounts.ts
> +  const accountSelectOptionsPlain = computed(() => prepareAccountsSelectOptions());
I suggest to add empty line after this one.

2023-04-25 09:45 UTC, peronczyk approved these changes

2023-04-25 10:01 UTC, csiarab commented
Lgtm

2023-04-25 10:07 UTC, Liubov-crypto commented
LGTM on web and extension

2023-04-25 16:52 UTC, merged