fix: remove buy tokens on ios devices
aeternity/superhero-wallet pull request #2032
Opened 2023-04-26 15:23 UTC by ifaouibadi

2023-04-27 12:22 UTC, pstachel approved these changes

2023-05-04 09:45 UTC, peronczyk requested changes

2023-05-04 09:45 UTC, peronczyk commented on src/background/popupHandler.ts
> +  const tabs: any[] = await browser.tabs.query({ active: true });
I don't see a reason for this change. The type is inherited from the `Browser` interface.

2023-05-09 07:24 UTC, peronczyk approved these changes

2023-05-15 20:22 UTC, merged