[SW-851] Update design of Account selection modal
aeternity/superhero-wallet pull request #2033
Opened 2023-04-26 22:44 UTC by pstachel

2023-04-27 16:46 UTC, Liubov-crypto commented
![sw-851](https://user-images.githubusercontent.com/69896204/234932832-5a42ad38-82c1-4449-92d3-a70e65f218d5.png)

2023-05-02 10:30 UTC, konradodo requested changes

2023-05-02 10:30 UTC, konradodo commented on src/popup/components/FormSelectOptionsHeader.vue
> +      v-if="options.length > 3"
3 -> Move that values to constans

2023-05-02 11:36 UTC, pstachel commented on src/popup/components/FormSelectOptionsHeader.vue
> +      emit('search', props.options);
Good catch, missed that one

2023-05-08 11:45 UTC, konradodo approved these changes

2023-05-08 11:45 UTC, konradodo approved these changes

2023-05-09 08:08 UTC, peronczyk requested changes

2023-05-09 08:08 UTC, peronczyk commented on src/popup/components/FormSelectOptionsHeader.vue
> +    function filterOptions(searchPhrase: string) {
This component should not do the actual filtering. Instead it should emit the search phrase and the parent component should react on this.

2023-05-18 08:48 UTC, peronczyk commented on src/popup/components/TokenAmount.vue
> +    }
I think it's bad to change the font weight of elements if we are changing the alignment. Those 2 things are not connected.

2023-05-18 08:48 UTC, peronczyk commented on src/popup/components/TokenAmount.vue
> +    alignRight: Boolean,
Why not using the CSS text-align on the parent level as this component is not a block but inline element?

2023-05-18 09:15 UTC, peronczyk approved these changes

2023-05-29 15:37 UTC, merged