refactor(middleware): use v2 endpoints
aeternity/superhero-wallet pull request #2095
Opened 2023-05-31 10:24 UTC by CedrikNikita

2023-05-31 11:39 UTC, peronczyk requested changes

2023-05-31 11:39 UTC, peronczyk commented on src/store/plugins/names.js
> +              .then(({ data }) => data.filter(({ active }) => active)
I suggest to move the `.filter` to the next line to make the code more readable.

2023-05-31 11:39 UTC, peronczyk commented on src/store/plugins/names.js
> +                  autoExtend: !!(
Next 2 lines should also be indented.

2023-05-31 11:39 UTC, peronczyk commented on src/composables/middleware.ts
I suggest to update the `fetchFromMiddleware` to use the `/v2` path by default. Now sometimes running this function requires using the `v2/` and sometimes no.

2023-05-31 11:39 UTC, peronczyk commented on src/composables/middleware.ts
> +              type: 'integer',
Are you sure this should be an integer?

2023-05-31 12:43 UTC, CedrikNikita commented on src/composables/middleware.ts
The `next` property including `/v2` in the route, and at this point we would need to make the logic of fetching all pages more complicated.

2023-05-31 13:02 UTC, Liubov-crypto commented
I can't see all my registered chain names in my account. On dev branch I can see them all.

2023-05-31 13:26 UTC, peronczyk commented on src/store/plugins/names.js
> +                  !!(
I don't see a reason to move this into new line. I think the way how it was before was OK.

2023-05-31 13:26 UTC, peronczyk approved these changes

2023-05-31 15:53 UTC, Liubov-crypto commented
The issue with names has been fixed. LGTM.

2023-06-01 11:40 UTC, Liubov-crypto commented
Retested, LGTM

2023-06-05 11:33 UTC, konradodo approved these changes

2023-06-09 10:31 UTC, merged