[SW-1002] add back arrow icon to "back to main accounts" button
aeternity/superhero-wallet pull request #2143
Opened 2023-06-27 21:21 UTC by konradodo

2023-06-27 21:24 UTC, pstachel commented on src/popup/components/ToggleMultisigButton.vue
> +          v-if="hasPendingMultisigTransaction"
I don't see a point in doing that if clause here

2023-06-27 21:27 UTC, pstachel commented on src/popup/components/ToggleMultisigButton.vue
> +    color: rgba($color-warning, 0.75);
So the square icon gets the opacity twice, right?

2023-06-28 09:06 UTC, CedrikNikita commented on src/icons/arrow-back.svg
> +<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
But we already have a back button icon.

2023-06-28 12:02 UTC, konradodo commented on src/icons/arrow-back.svg
> +<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
good point, i found and replaced it

2023-06-28 12:04 UTC, pstachel approved these changes

2023-06-28 12:17 UTC, peronczyk requested changes

2023-06-28 12:17 UTC, peronczyk commented on src/popup/components/ToggleMultisigButton.vue
> +          class="icon"
I think it's a bad change to shorten the class name. Those two icons used in this component has different styles. Maybe you can share the common part this way:

```
.icon-foo,
.icon-bar {
  // Common styles
}
```

2023-06-28 12:17 UTC, peronczyk commented on src/popup/components/ToggleMultisigButton.vue
> +      </span>
I don't see a reason for this change.

2023-06-28 12:17 UTC, peronczyk commented on src/popup/components/ToggleMultisigButton.vue
> +        </span>
I don't see a reason for this change.

2023-06-28 12:29 UTC, konradodo commented on src/popup/components/ToggleMultisigButton.vue
> +      </span>
for increased readability

2023-06-28 12:30 UTC, konradodo commented on src/popup/components/ToggleMultisigButton.vue
> +        </span>
for increased readability

2023-07-05 08:11 UTC, peronczyk commented on src/popup/components/ToggleMultisigButton.vue
> +        <span> {{ $t('common.tx') }} </span>
Please remove the spaces around the `{{ ... }}`.

2023-07-05 08:11 UTC, peronczyk commented on src/popup/components/ToggleMultisigButton.vue
> +      <span class="text"> {{ $t('multisig.showMultisigVaults') }} </span>
Please remove the spaces around the `{{ ... }}`.

2023-07-05 08:11 UTC, peronczyk approved these changes

2023-07-05 08:14 UTC, CedrikNikita requested changes
Last commit is an obvious mistake.

2023-07-05 11:36 UTC, peronczyk commented
Yeah, last commit should be removed.

2023-07-12 09:15 UTC, merged