[SW-1247] feat: improve invite links
aeternity/superhero-wallet pull request #2319
Opened 2023-09-05 11:34 UTC by CedrikNikita

2023-09-05 13:26 UTC, Liubov-crypto commented
LGTM

2023-09-06 12:39 UTC, Liubov-crypto commented
LGTM

2023-09-11 09:16 UTC, peronczyk requested changes

2023-09-11 09:16 UTC, peronczyk commented on src/popup/components/AccountSelector.vue
> +  .address-truncated {
There is no such class in the template.

2023-09-11 09:16 UTC, peronczyk commented on src/popup/components/AddressTruncated.vue
> +    showProtocolIcon: Boolean,
Please move this line below the `protocol`. The reason is that it's a good pattern to group Boolean props together. Also it makes more sense in terms of alphabetical order.

2023-09-11 09:16 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +        <span>{{ `${amount} AE` }}</span>
```suggestion
        <span>{{ amount }} {{ AE_SYMBOL }}</span>
```

2023-09-11 09:16 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +  computed, defineComponent, ref, PropType, onMounted,
I suggest to split this line.

2023-09-11 09:16 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +import type { RejectCallback, ResolveCallback, ObjectValues } from '../../../types';
I suggest to put the `types` import above all local imports and use the `@` in the import path.

2023-09-11 09:16 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +    @extend %face-sans-16-medium;
Please put the extend at the beginning of the definitions for this class.

2023-09-11 09:16 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +    .gray {
Name "gray" has nothing to do with the opacity and margin.

2023-09-11 09:16 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +      :deep(.truncate) {
Parent components should not affect child component internals. So please avoid using `:deep` selector. If you want to make a child component to behave or look differently please use bool prop and update the child component itself.

2023-09-11 09:16 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +    @extend %face-sans-19-medium;
Please put the extend at the top of the class definitions.

2023-09-11 09:16 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +  :deep(.container) {
Parent components should not affect child component internals. So please avoid using :deep selector. If you want to make a child component to behave or look differently please use bool prop and update the child component itself.

2023-09-11 09:16 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +@use '../../../styles/typography';
You can use `@` in the paths.

2023-09-11 09:28 UTC, peronczyk requested changes

2023-09-11 09:28 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +          @click="handleMainButtonClick"
```suggestion
          @click="handleMainButtonClick()"
```
This avoids passing the click event as the 1st function argument.

2023-09-11 09:28 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +          {{ $t('common.max') }}
I suggest to use `text` prop to make the code slimmer.

2023-09-11 09:28 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +        Tag.SpendTx, // https://github.com/aeternity/aepp-sdk-js/issues/1852
Wrong indentation.

2023-09-11 09:28 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +    const currencyFormatted = computed(() => getFormattedFiat(+amount.value));
I suggest to move the computed properties before the function definitions.

2023-09-11 09:28 UTC, peronczyk commented on src/popup/components/Modals/ClaimGiftCard.vue
> +    color: #00d3a1;
Please use colors saved in the variables file. If it's a new color add it to mentioned file.

2023-09-11 09:53 UTC, peronczyk requested changes

2023-09-11 09:53 UTC, peronczyk commented on src/store/modules/invites.js
> +      secretKey, recipientId, amount = undefined, isMax,
Please split this line.

2023-09-11 09:53 UTC, peronczyk commented on src/protocols/aeternity/helpers/index.ts
> +const SEED_LENGTH = 32;
I suggest to move this into global constants file as this is not a "helper" and we use the same seed for all the protocols.

2023-09-11 09:53 UTC, peronczyk commented on src/protocols/aeternity/helpers/index.ts
> +    ? nacl.sign.keyPair.fromSeed(Buffer.from(secretKey)).secretKey : Buffer.from(secretKey));
```suggestion
  return new MemoryAccount(
    Buffer.from(secretKey).length === SEED_LENGTH
      ? nacl.sign.keyPair.fromSeed(Buffer.from(secretKey)).secretKey
      : Buffer.from(secretKey),
  );
```
Please make it more readable by splitting the line.

2023-09-15 09:17 UTC, peronczyk approved these changes

2023-09-15 09:22 UTC, pstachel commented on src/store/modules/invites.js
> +          1,
I think we should avoid magic numbers

2023-09-15 09:36 UTC, pstachel approved these changes

2023-09-15 09:51 UTC, Liubov-crypto commented
LGTM

2023-09-15 09:55 UTC, merged