[SW-1254] Refactor TransactionDetailsBase component
aeternity/superhero-wallet pull request #2336
Opened 2023-09-13 14:45 UTC by pstachel

2023-09-15 07:05 UTC, peronczyk requested changes

2023-09-15 07:05 UTC, peronczyk commented on src/popup/components/TransactionDetailsBase.vue
> +    showAmount: { type: Boolean, default: true },
I strongly recommend to not use the bool props with the default value of `true`. If you want to display something by default I suggest to inverse the name, e.g.: `hideAmount`.

2023-09-22 09:19 UTC, konradodo approved these changes

2023-09-27 11:57 UTC, peronczyk commented on src/popup/components/TransactionDetailsBase.vue
> +    hideAmount: Boolean,
Can you please move the boolean props to the end of props list? That's a common pattern within the industry.

2023-10-05 10:47 UTC, merged