[SW-504, SW-1000] Do not depend on http compiler
aeternity/superhero-wallet pull request #2338
Opened 2023-09-14 10:38 UTC by CedrikNikita

2023-09-14 11:15 UTC, Liubov-crypto commented
LGTM

2023-09-15 06:52 UTC, subhod-i requested changes
There are translation keywords related to the compiler. 
`networkCompilerPlaceholder`
`networkCompilerLabel`

These could be removed.

2023-09-15 06:54 UTC, subhod-i commented
Great PR.

2023-09-15 07:17 UTC, peronczyk commented on src/popup/components/Modals/ConfirmTransactionSign.vue
> +          txParams = {
I suggest to have different variable name here instead of reassigning it.

2023-09-15 07:21 UTC, peronczyk approved these changes

2023-09-15 07:39 UTC, subhod-i approved these changes

2023-09-15 08:17 UTC, Liubov-crypto commented
LGTM

2023-09-15 08:25 UTC, merged