[SW-1265] Make transaction history the active tab on account details screen
aeternity/superhero-wallet pull request #2350
Opened 2023-09-18 15:25 UTC by pstachel

2023-09-22 09:13 UTC, konradodo approved these changes

2023-09-25 08:39 UTC, CedrikNikita approved these changes

2023-10-02 08:27 UTC, peronczyk requested changes

2023-10-02 08:27 UTC, peronczyk commented on src/popup/router/routes.ts
> +        redirect: { name: ROUTE_MULTISIG_DETAILS_TRANSACTIONS },
Please avoid using redirects. The child page, that should be opened as the default should have the path set as empty string.

2023-10-05 10:36 UTC, peronczyk commented on src/popup/router/routeNames.ts
> +export const ROUTE_MULTISIG_DETAILS_ASSETS = 'multisig-account-details-assets';
The name of this constant should not be changed.

2023-10-05 10:37 UTC, peronczyk commented on src/popup/router/routeNames.ts
> +export const ROUTE_ACCOUNT_DETAILS_ASSETS = 'account-details-assets';
The name of this constant should not be changed.

2023-10-06 07:00 UTC, peronczyk approved these changes

2023-10-06 10:37 UTC, merged