fix: seed-phrase verification button not fixed to bottom
aeternity/superhero-wallet pull request #3074
Opened 2024-05-28 10:24 UTC by martinkaintas

closes #2939

2024-06-19 07:28 UTC, peronczyk requested changes

2024-06-19 07:28 UTC, peronczyk commented on src/popup/components/FixedScreenFooter.vue
> +    positionFixed: Boolean,
The initial idea of this component was to be fixed whenever used. I think having additional property that fixes it even more.

2024-07-11 14:13 UTC, Liubov-crypto commented
LGTM

2026-05-17 18:54 UTC, CedrikNikita approved these changes

2026-05-17 18:54 UTC, merged