Inject Youtube tip button
aeternity/superhero-wallet pull request #433
Opened 2020-07-27 08:05 UTC by etharner

Closes #429.

2020-08-04 07:01 UTC, davidyuk commented on src/content-scripts/tipButton.js
> +    e.stopPropagation();
@mradkov why do we need `stopPropagation` here?

2020-08-04 07:10 UTC, davidyuk commented on src/content-scripts/tipButton.js
> +    e.stopPropagation();
In general, I would suggest to define hover styles using css.

2020-08-19 14:25 UTC, etharner commented on src/content-scripts/tipButton.scss
> +        filter: invert(52%) sepia(46%) saturate(3166%) hue-rotate(186deg) brightness(100%) contrast(104%);
I propose to use that hack (https://codepen.io/sosuke/pen/Pjoqqp) instead of loading other icon

2020-08-20 07:41 UTC, mradkov requested changes
The button I see on YT does not have the appropriate style.

![Screenshot 2020-08-20 at 10 40 03](https://user-images.githubusercontent.com/13139371/90730938-a3a89c80-e2d1-11ea-99a6-143c0744ebd0.png)

2020-08-20 14:35 UTC, etharner commented on src/content-scripts/tipButton.js
> +const style = document.createElement('link');
I used solution proposed here [https://stackoverflow.com/a/9721569]()

2020-08-25 08:30 UTC, mradkov approved these changes
Looks good now, thanks @etharner.

2020-08-25 08:30 UTC, merged