Add auto-extending of names
aeternity/superhero-wallet pull request #494
Opened 2020-09-04 08:20 UTC by etharner

Closes #491.

2020-09-04 09:00 UTC, mradkov commented on src/store/plugins/names.js
> +            if (name.expiresAt <= height && oldName.autoExtend) {
I think the logic here is wrong. 

If the `height` is gt than `name.expiresAt` then the name would have been already expired. 🤔 

Maybe just auto extend without checking the height?

2020-09-04 09:30 UTC, mradkov commented on src/store/plugins/names.js
> +            if (name.expiresAt <= height && oldName.autoExtend) {
```suggestion
            if (name.expiresAt >= height && oldName.autoExtend) {
```

This way we will ensure we dispatch updatePointer only in the case when the current block height has not reached the name's expiration date.

2020-09-04 09:42 UTC, mradkov requested changes
Also while testing - the name extend popup appears every few seconds when I'm on the `Names` page.

Let's make it fire only once at opening the extension.

2020-09-07 07:12 UTC, etharner commented on src/popup/utils/constants.js
> +export const AUTO_EXTEND_NAME_BLOCKS_INTERVAL = 100;
Let's maybe use some interval between blocks when we will be asking for extending, and I also call it only on extension opening

2020-09-10 10:31 UTC, mradkov approved these changes

2020-09-10 10:32 UTC, merged