Make pending transaction polling more accurate
aeternity/superhero-wallet pull request #556
Opened 2020-10-19 16:56 UTC by davidyuk

2020-10-20 07:05 UTC, davidyuk commented on src/popup/router/components/PendingTxs.vue
> -          this.$store.commit('setPendingTxs', pending);
The transaction is not removed if it can't be mined.

2020-10-20 07:05 UTC, davidyuk commented on src/popup/router/components/PendingTxs.vue
> -    const checkMined = setInterval(() => this.checkPendingTxMined(), 2500);
There is no guarantee that internal pulling will end in 2.5s, so several pullings can be started at the same time.

2020-10-29 09:45 UTC, CedrikNikita requested changes
Steps to reproduce:
1. Try to withdraw
2. On success tip view
```Cannot read property 'amount' of undefined```

2020-11-05 00:19 UTC, davidyuk commented on src/store/plugins/pendingTransactionHandler.js
> +            params: { redirectstep: 3, successtx: transaction },
I have misunderstood this part and instead `transaction` here was `true` that was causing the exception:
> Cannot read property 'amount' of undefined

2020-11-05 05:46 UTC, CedrikNikita approved these changes
Changes look reasonable, would be nice if @Liubov-crypto would check it.

2020-11-05 11:31 UTC, Liubov-crypto commented
I got an error when trying to make a tip.
Steps to reproduce behaviour:
1. Open feature-refactor-pending-transactions.wallet.z52da5wt.xyz
2. Login into account
3. Click on Send Tip
4. See an error
![Знімок екрана 2020-11-05 о 12 58 00 пп](https://user-images.githubusercontent.com/69896204/98233673-0ff97a80-1f68-11eb-80b2-24d55bd1076e.png)
![Знімок екрана 2020-11-05 о 12 59 53 пп](https://user-images.githubusercontent.com/69896204/98233716-1c7dd300-1f68-11eb-8fb7-ddf07b4d8bbb.png)

![Знімок екрана 2020-11-05 о 12 26 42 пп](https://user-images.githubusercontent.com/69896204/98233626-007a3180-1f68-11eb-8946-1b8041a26939.png)
![Знімок екрана 2020-11-05 о 1 01 15 пп](https://user-images.githubusercontent.com/69896204/98233918-54851600-1f68-11eb-9efb-51bf42a833b5.png)


There was also an error when sending a report via the wallet:

![Знімок екрана 2020-11-05 о 12 27 53 пп](https://user-images.githubusercontent.com/69896204/98233854-420adc80-1f68-11eb-9952-d1ea95034e12.png)
![Знімок екрана 2020-11-05 о 1 00 33 пп](https://user-images.githubusercontent.com/69896204/98233897-4e8f3500-1f68-11eb-9954-ed78abb5dfe0.png)

Register a .chain name - does not work:

![Знімок екрана 2020-11-05 о 1 13 57 пп](https://user-images.githubusercontent.com/69896204/98234242-d2492180-1f68-11eb-9e90-53e511c7956d.png)
 
![Знімок екрана 2020-11-05 о 1 13 37 пп](https://user-images.githubusercontent.com/69896204/98234384-07ee0a80-1f69-11eb-82a4-f1d3d3026d08.png)

Withdrawal works good. There is a transaction delay of about 2 - 2.5 seconds, as described by Denis.

Chrome, Version 86.0.4240 (Mac OS)
OS 10.15.7

2020-11-05 12:15 UTC, Liubov-crypto commented
I created a new account, then deleted it, and when I logged in to the existing one I got these errors:

![Знімок екрана 2020-11-05 о 1 35 45 пп](https://user-images.githubusercontent.com/69896204/98236721-7da7a580-1f6c-11eb-951c-aa31f0a48cf6.png)
![Знімок екрана 2020-11-05 о 1 35 58 пп](https://user-images.githubusercontent.com/69896204/98236734-813b2c80-1f6c-11eb-97bc-794d77cc3bb9.png)
![Знімок екрана 2020-11-05 о 1 36 13 пп](https://user-images.githubusercontent.com/69896204/98236741-84ceb380-1f6c-11eb-86b9-a929e5f6290f.png)

I used the Tip button on Youtube and Twitter to sent tips. Transactions in my wallet are marked Pending (Invalid date) but tokens have been sent and I see them on sh feed:
![Знімок екрана 2020-11-05 о 2 01 16 пп](https://user-images.githubusercontent.com/69896204/98238646-628a6500-1f6f-11eb-8269-d78e725fe4c8.png)

Transaction on the mainnet: 
https://mainnet.aeternal.io/transactions/th_gbRWkpenAhf7QYP6LHEwH3xB639taqwwpHCKbK7PYqCW4S9Vb
https://mainnet.aeternal.io/transactions/th_dMCcZZFn1nFZAuqjjcKbEXg3bDjFwoiHFvifSY2xfobcQHL6R
https://mainnet.aeternal.io/transactions/th_UQBpirdyiAaiNQFEiVteaQUrmh6PmZ5CY74bcWJEQ2pQrMmom

Browser: FF ver. 0.82
Extension for FF: Superhero 867f0d7 / v.0.3.3

2020-11-06 11:54 UTC, davidyuk commented
With @Liubov-crypto we agreed that she will update the list of bugs leaving the only one that do not persist in the develop branch to be focused on things broke in this PR.

2020-11-10 15:23 UTC, Liubov-crypto commented
I used the Tip button on Youtube and Twitter to sent tips. Transactions in my wallet are marked Pending (Invalid date) but tokens have been sent and I see them on sh feed. Also, I see the same (pending) transactions marked as sent in my wallet:

![Знімок екрана 2020-11-10 о 4 46 59 пп](https://user-images.githubusercontent.com/69896204/98689266-69044c80-2374-11eb-835e-7835fecd3dab.png)

https://mainnet.aeternal.io/transactions/th_r3Yv52tLabYutuUC8wq237WyfJGhGJ7nSScYJUCF1zDwa8Udh
https://mainnet.aeternal.io/transactions/th_246smAbAhsQRRJKH67gpav3zjcUhrdX2z7ywwygjH6L7JdeyKq

Browser: FF ver. 0.82
Chrome ver. 86.0.4240 (Mac OS)
Superhero 867f0d7 / v.0.3.3

2020-11-18 07:20 UTC, mradkov approved these changes
Code changes look good.

2020-11-20 16:24 UTC, merged