Refactoring
aeternity/superhero-wallet pull request #562
Opened 2020-10-21 10:16 UTC by CedrikNikita

2020-10-21 11:05 UTC, mradkov commented
I would like https://github.com/aeternity/superhero-wallet/pull/519 to be merged first and then apply these changes on-top.

2020-11-18 21:08 UTC, davidyuk requested changes
Proposing to extract obvious commits to a separate PR to merge them earlier.

2020-11-18 21:08 UTC, davidyuk commented on src/store/plugins/observables.js
> +    multicast(new BehaviorSubject(0)),
The initial value of the previous balance implementation was persisted in localStorage (as I understand, to don't show 0 at startup). Shouldn't we consider this feature as important and keep it in this implementation?

2020-11-18 21:08 UTC, davidyuk commented on src/store/plugins/observables.js
> +    balanceCurrency: balance$.pipe(map(bal => store.getters.currentCurrencyRate * bal)),
The `balanceCurrency` won't be updated if `getters.currentCurrencyRate` changed. Would be more accurate to subscribe to `currentCurrencyRate` using `watchAsObservable`

2020-11-18 21:08 UTC, davidyuk commented on src/store/plugins/observables.js
> +          ? store.state.tokens[store.state.current.token].balance
The balance will remain polled even if the balance of the tokens is shown.

2020-11-22 16:49 UTC, davidyuk commented on src/store/plugins/observables.js
> +    chainName: store.state.chainNames && store.state.chainNames[sender],
```suggestion
    chainName: store.state.chainNames?.[sender],
```
this is not the same as https://github.com/aeternity/superhero-wallet/pull/562#discussion_r526400981

2020-11-25 04:33 UTC, davidyuk approved these changes
Despite remarks, I think we can merge that

2020-11-25 04:33 UTC, davidyuk commented on src/popup/router/pages/Send.vue
> +        hash: this.$t('pages.send.hash'),
This approach makes it more difficult to track is wording actually used or not

2020-11-25 04:33 UTC, davidyuk commented on src/popup/router/pages/Send.vue
>            </div>
This looks ok but a more component-oriented approach would be to extract InfoGroup component and exactly specify fields without a cycle:
```suggestion
          <InfoGroup
            :value="account.publicKey"
            :label="$t('pages.send.sender')"
          />
          <InfoGroup
            :value="form.address"
            :label="$t('pages.send.recipient')"
          />
```
the necessity to pass `data-cy` is just crap, e2e tests shouldn't require that

2020-11-25 07:51 UTC, davidyuk commented on src/popup/router/pages/Send.vue
>            </div>
Actually, we may apply `data-cy` on InfoGroup and to make selectors on e2e side a bit more complex.

2020-11-26 06:23 UTC, davidyuk approved these changes

2020-11-26 06:24 UTC, merged