Set language on loading
aeternity/superhero-wallet pull request #700
Opened 2020-12-03 03:56 UTC by CedrikNikita

fixes #691

2020-12-07 07:40 UTC, etharner requested changes

2020-12-07 12:33 UTC, CedrikNikita commented on src/store/actions.js
> +    fetchAndSetLocale(language);
Actually i agree with that.

2020-12-10 10:40 UTC, davidyuk approved these changes

2020-12-10 10:40 UTC, davidyuk commented on src/store/plugins/languages.js
> +export const fetchAndSetLocale = async (languageCode) => {
```suggestion
const fetchAndSetLocale = async (languageCode) => {
```

2020-12-10 10:40 UTC, davidyuk commented on src/store/plugins/languages.js
> +export const preferredLocale = (() => {
```suggestion
const preferredLocale = (() => {
```

2020-12-10 10:40 UTC, davidyuk commented on src/store/plugins/languages.js
> +      activeCode: store.state.languages ? store.state.languages.activeCode : preferredLocale,
Let's write it in a modern way 😄
```suggestion
      activeCode: store.state.languages?.activeCode || preferredLocale,
```

2020-12-10 12:15 UTC, etharner approved these changes
Cool, LGTM

2020-12-10 12:15 UTC, merged

2020-12-10 15:14 UTC, Liubov-crypto commented
Tested, looks good on my side.